name: jcc
description: Jamnagar Corporation Care

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^11.1.3
#  UI Libs
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.7
#  Bloc Libs
  equatable: ^2.0.5
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
#  Firebase Libs
  firebase_core:
  cloud_firestore:
  firebase_auth:
  google_sign_in:
  otpview_sk: ^0.0.2
  otpview: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf

    - family: Roboto Thin
      fonts:
        - asset: assets/fonts/Roboto-Thin.ttf

    - family: Roboto Condensed
      fonts:
        - asset: assets/fonts/RobotoCondensed-Regular.ttf

  assets:
    - assets/
    - assets/icons/
    - assets/backgrounds/

