// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8Wl9-5vRRsSbHCH4h9-VIp0HJRXp92jc',
    appId: '1:284598395132:web:c940bf037ee5cfd0657779',
    messagingSenderId: '284598395132',
    projectId: 'coders-flow',
    authDomain: 'coders-flow.firebaseapp.com',
    storageBucket: 'coders-flow.appspot.com',
    measurementId: 'G-ZVJZWYMDF1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7RVyZ_VPR_rdCtNepvs2srnzO8l4MMeo',
    appId: '1:284598395132:android:7bd4746bdb8f51fb657779',
    messagingSenderId: '284598395132',
    projectId: 'coders-flow',
    storageBucket: 'coders-flow.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoFZI1izmKXtz187A9Ms0h0eIVq3yFoeU',
    appId: '1:284598395132:ios:f9493c0412b02815657779',
    messagingSenderId: '284598395132',
    projectId: 'coders-flow',
    storageBucket: 'coders-flow.appspot.com',
    iosBundleId: 'com.jcc.jcc',
  );
}
